# -*- coding: utf-8 -*-
"""day4_homework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USst3Sh9bBNyz7R5xLGqNSHAZTkOu_t8
"""

prime_numbers = 0

def check_prime_number(x):
    if x >= 2:
        for y in range(2,x):
            if not ( x % y ):
                return False
    else:
	    return False
    return True
	        

for i in range(0,100):
    if check_prime_number(i):
        prime_numbers += 1
        print(i)