# -*- coding: utf-8 -*-
"""day5_homework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wTbCOKqBNXp3H9qspuzOT49dxN4u4Izi
"""

class Animals:
  def __init__ (self, species, legnumber, diet ):
      self.animalspecies = species
      self.animallegnumber = legnumber
      self.animaldiet = diet
  def printspecies(self):
    print("This animal is in " + self.animalspecies + "species")
  
  def printlegs(self):
    print ("This animal has " + self.animallegnumber + "legs")
  def printdiet(self):
    print ("The "+ self.animalspecies + "is a " + self.animaldiet + " animal" )
class Cats(Animals):
    pass
class Dogs(Animals):
    pass
cats = Cats("Felis Catus","4","carnivorous")
dogs = Dogs("Canis familiaris", "4", "carnivorous")

cats.printspecies()
dogs.printdiet()