# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaIRtwnGyfvE8_bgxwMrA7LZOFfb3jit
"""

print("Please enter your credentials:")

  username = "Batman"
  password = "imbatman"

  username_user = input("Username: ")
  password_user = input("Password: ")

  if (username != username_user and password == password_user):
    print("You are not Batman. Change your username")
  elif (username == username_user and password != password_user):
    print("Incorrect password, Batman!")
  elif ( username != username_user and password != password_user):
    print("Who are you? Incorrect username and password!")
  else:
    print("Welcome home, Batman!)")

print("Please enter your credentials:")

credentials = {"username": "Batman","password":"imbatman" }


username_user = input("Username: ")
password_user = input ("Password: ")

if (username_user not in credentials.values() and password_user in credentials.values()):
   print("You are not Batman. Change your username")
elif (username_user in credentials.values() and password_user not in credentials.values()):
  print("Incorrect password, Batman!")
elif ( username_user not in credentials.values() and password_user not in credentials.values()):
  print("Who are you? Incorrect username and password!")
else:
    print("Welcome home, Batman!)")