# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mEgqsXDhslekUkF4K-eIU1Pgnj5T1wXJ
"""

list1 = [1,2,3,4,5,6]
length = len(list1)
print(length)
middle = int(length/2)
print(middle)
list1_1 = list1[:middle]
print(list1_1)

list1_2 = list1[middle:]
print(list1_2)

list1_2.extend(list1_1)
print(list1_2)

n = int(input("Please enter a single digit number: "))
if n <= 0:
  print("Please enter a positive single digit number")
elif (n > 0 and n < 10):
 for i in range(n+1):
  if i % 2 == 0:
    print(i)
elif n >=10:
  print("Please enter a single digit number")
else:
  print("Unknown Error")

